"""Local transport-orbit quotient geometry for TARDIS innovations."""

from __future__ import annotations

from dataclasses import dataclass

import torch
import torch.nn.functional as functional
from torch import nn


@dataclass(frozen=True, slots=True)
class TransportOrbitBasis:
    """Damped local tangent basis induced by infinitesimal latent transport."""

    gradient_x: torch.Tensor
    gradient_y: torch.Tensor
    gram_xx: torch.Tensor
    gram_xy: torch.Tensor
    gram_yy: torch.Tensor
    determinant: torch.Tensor
    visibility: torch.Tensor
    tangent_rank: torch.Tensor


@dataclass(frozen=True, slots=True)
class QuotientDecomposition:
    """Exact split into transport-tangent correction and quotient innovation."""

    tangent: torch.Tensor
    innovation: torch.Tensor
    flow_coefficients: torch.Tensor
    tangent_rank: torch.Tensor


class TransportOrbitProjector(nn.Module):
    """Quotient out changes explained by the local Jacobian of latent warping.

    At each latent location, the spatial derivatives of the transported prior
    span the first-order orbit generated by a small two-dimensional flow update.
    The projector removes this motion-tangent component before diffusion.
    """

    def __init__(
        self,
        *,
        regularization: float = 1.0e-4,
        rank_threshold: float = 1.0e-5,
        detach_basis: bool = True,
    ) -> None:
        super().__init__()
        if regularization <= 0 or rank_threshold <= 0:
            raise ValueError("quotient regularization and rank threshold must be positive")
        self.regularization = regularization
        self.rank_threshold = rank_threshold
        self.detach_basis = detach_basis

    def build_basis(
        self,
        transported_prior: torch.Tensor,
        visibility: torch.Tensor,
    ) -> TransportOrbitBasis:
        """Build one reusable local transport basis for a video transition."""

        if transported_prior.ndim != 4:
            raise ValueError("transported_prior must have shape [B,C,H,W]")
        expected_visibility = (
            transported_prior.shape[0],
            1,
            *transported_prior.shape[-2:],
        )
        if visibility.shape != expected_visibility:
            raise ValueError("visibility must have shape [B,1,H,W]")

        reference = transported_prior.detach() if self.detach_basis else transported_prior
        compute_dtype = (
            torch.float32 if reference.dtype in {torch.float16, torch.bfloat16} else reference.dtype
        )
        reference = reference.to(compute_dtype)
        confidence = visibility.detach().to(compute_dtype).clamp(0, 1)
        gradient_x, gradient_y = _centered_spatial_gradients(reference)
        gram_xx = (gradient_x * gradient_x).sum(dim=1, keepdim=True)
        gram_xy = (gradient_x * gradient_y).sum(dim=1, keepdim=True)
        gram_yy = (gradient_y * gradient_y).sum(dim=1, keepdim=True)
        trace = gram_xx + gram_yy
        discriminant = ((gram_xx - gram_yy).square() + 4 * gram_xy.square()).sqrt()
        eigenvalue_max = 0.5 * (trace + discriminant)
        eigenvalue_min = 0.5 * (trace - discriminant)
        tangent_rank = (
            (eigenvalue_max > self.rank_threshold).to(compute_dtype)
            + (eigenvalue_min > self.rank_threshold).to(compute_dtype)
        ) * confidence
        local_scale = (gram_xx + gram_yy).detach().clamp_min(self.rank_threshold)
        ridge = self.regularization * local_scale
        regularized_xx = gram_xx + ridge
        regularized_yy = gram_yy + ridge
        determinant = (regularized_xx * regularized_yy - gram_xy.square()).clamp_min(
            torch.finfo(compute_dtype).eps
        )
        return TransportOrbitBasis(
            gradient_x=gradient_x,
            gradient_y=gradient_y,
            gram_xx=regularized_xx,
            gram_xy=gram_xy,
            gram_yy=regularized_yy,
            determinant=determinant,
            visibility=confidence,
            tangent_rank=tangent_rank,
        )

    def decompose(
        self,
        value: torch.Tensor,
        basis: TransportOrbitBasis,
    ) -> QuotientDecomposition:
        """Split ``value`` into motion-tangent and quotient-normal components."""

        if value.ndim != 4 or value.shape != basis.gradient_x.shape:
            raise ValueError("value and transport basis must share [B,C,H,W]")
        original_dtype = value.dtype
        value_compute = value.to(basis.gradient_x.dtype)
        rhs_x = (basis.gradient_x * value_compute).sum(dim=1, keepdim=True)
        rhs_y = (basis.gradient_y * value_compute).sum(dim=1, keepdim=True)
        coefficient_x = (basis.gram_yy * rhs_x - basis.gram_xy * rhs_y) / basis.determinant
        coefficient_y = (basis.gram_xx * rhs_y - basis.gram_xy * rhs_x) / basis.determinant
        coefficients = torch.cat((coefficient_x, coefficient_y), dim=1)
        tangent = (
            basis.gradient_x * coefficient_x + basis.gradient_y * coefficient_y
        ) * basis.visibility
        tangent = tangent.to(original_dtype)
        innovation = value - tangent

        return QuotientDecomposition(
            tangent=tangent,
            innovation=innovation,
            flow_coefficients=(
                coefficients.to(original_dtype) * basis.visibility.to(original_dtype)
            ),
            tangent_rank=basis.tangent_rank.to(original_dtype),
        )


def _centered_spatial_gradients(value: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    horizontal = functional.pad(value, (1, 1, 0, 0), mode="replicate")
    vertical = functional.pad(value, (0, 0, 1, 1), mode="replicate")
    gradient_x = 0.5 * (horizontal[..., 2:] - horizontal[..., :-2])
    gradient_y = 0.5 * (vertical[..., 2:, :] - vertical[..., :-2, :])
    return gradient_x, gradient_y


__all__ = [
    "QuotientDecomposition",
    "TransportOrbitBasis",
    "TransportOrbitProjector",
]
